### PR TITLE
Additional steps for switching between different Pmem modes

### PR DESCRIPTION
**Pull request by aarati-K**

### CODE REVIEW

**Comment by aarati-K** [comment]
@gaffneyk Can you take a look at this PR?

**Comment by kpgaffney** [comment]
Looks good to me!

**Comment by aarati-K** [comment]
@gaffneyk Thanks! I currently don't have write access to this repository, so I'm unable to merge this pull request. Would it be possible for you to give me write access?

**Comment by kpgaffney** [comment]
Sure, you should be able to merge it now.

**Pull request merged**
